server:
  port: 8888
spring:
  application:
    name: KUANGGOU-PLAT

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/